### PR TITLE
Updated client CA cert

### PR DESCRIPTION
**Pull request by feldsam**
Hi, on some systems I was getting error

```
Code:0 Message:cURL error 60: Peer's certificate issuer has been marked as not trusted by the user. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://fioapi.fio.cz/v1/rest/
```

and I figured out, that shipped certificate have to be updated

### CODE REVIEW

**Comment by mhujer** [comment]
@feldsam Hi, thanks for the PR! I'm not sure that including the certificate in the repo still makes sense. Maybe it would be better if it depended on `composer/ca-bundle` directly? What do you think?

//cc @soukicz ?

**Comment by feldsam** [comment]
There is actually dep on \Kdyby\CurlCaBundle\CertificateHelper, but there is also fallback, if this is not installed. So I just updated fallback cert.

But, it makes sense move suggest dep to required dep and drop fallback

**Comment by soukicz** [comment]
>  I'm not sure that including the certificate in the repo still makes sense

It is nice that it can run without dependencies. And it is just fallback because it is already using composer/ca-bundle if it is available.

**Comment by feldsam** [comment]
There is still `guzzlehttp/guzzle` dep and I think, that it is better to use ca-bundle instead of maintaining cert in repo as @mhujer  pointed.

**Comment by feldsam** [comment]
So I updated my commit to remove fallback and cert from repo and refactored code to use ca-bundle only

**Comment by mhujer** [comment]
@feldsam thanks! merged and tagged as `5.0.0`

**Pull request merged**
